/*
Student Name 	:Aarush Baba Rijal
Subject 	:Programing Fundamentals
Roll no.	:01
Program		:To print sum of two numbers
Lab no.		:02
Date 		:19 September,2016
*/
#include<stdio.h>
#include<conio.h>
	void main()
		{
		int a,b,c,sum;
		clrscr();
		printf("Enter first number:\n") ;
		scanf("%d",&a);
		printf("Enter second  number:\n");
		scanf("%d",&b);
		printf("Enter third number:\n");
		scanf("%d",&c);
		sum = a+b+c;
		printf("The sum of given three number is: \n%d",sum);
		getch();
		}


